name: auto upd version
on:
  pull_request:
    types : opened
    branches:
      - 2022.2_new_features
    paths:
      - '**.ts'
  workflow_dispatch:

jobs:
  build-extensions:
    runs-on: [self-hosted, linux]
    container: node:14-buster
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Update version of extension
        run: |
          git fetch
          git checkout "$GITHUB_HEAD_REF"
          npm --no-git-tag-version version patch
          git config user.name ci
          git config user.email cd4iss@intel.com
          git commit -a -m "upd version"
          git push 
